#!/bin/bash

echo "------ HOOK START - BUILD -------"
export $(cat ./.env)
printenv

docker build --build-arg S6_OVERLAY_VERSION="${S6_OVERLAY_VERSION}" \
    -t "${IMAGE_NAME}" .

echo "------ HOOK END - BUILD -------"
